print("Padam Rai.")
print("I'm from Phidim.")
print("I'm a Lower Secondary Level teacher.")
print("I love teaching.")
print("I'm learning computer.")
print("I go to school everyday.")
print("I drive motorbike everyday.")
print("I'm studying now.")
print("I'm interested in learning computer.")
print("I'm teaching in a village school.")
